# Generated by Django 3.0.2 on 2020-01-08 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='coords',
            field=models.CharField(default='DEFAULT COORDS', max_length=50),
        ),
    ]
