# Generated by Django 3.0.2 on 2020-01-09 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0002_auto_20200109_0906'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='seen_room',
            new_name='seen_rooms',
        ),
    ]
