# Generated by Django 3.0.2 on 2020-01-09 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0004_auto_20200109_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='seen_rooms',
            field=models.CharField(default=models.IntegerField(default=0), max_length=1000),
        ),
    ]
